spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rap_phim_online?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


app:
  jwtSecret: RapPhimSecretKey123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  jwtExpirationMs: 86400000


server:
  port: 8080